name: Generate Images JSON

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate JSON files
        run: |
          for dir in gallery_*/; do
            if [ -d "$dir" ]; then
              echo "Processing $dir..."
              cd "$dir"
              # Find all files ending with .jpg, sort them, and format as JSON
              find . -maxdepth 1 -type f -iname "*.jpg" | sort | awk -F'/' '{printf "\"%s\",\n", $2}' | sed '$s/,$//' > images_list.json
              # Add JSON array brackets
              sed -i '1s/^/[/' images_list.json
              echo "]" >> images_list.json
              mv images_list.json images.json
              cd ..
            fi
          done
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Generated images.json files'
          file_pattern: 'gallery_*/images.json'
