name: Generate JSON for image galleries

on:
  push:
    paths:
      - 'gallery_*/**'
    branches: [ main ]

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate JSON for each gallery
        run: |
          for gallery in gallery_*; do
            if [ -d "$gallery" ]; then
              json_file="$gallery/images.json"
              echo "[" > "$json_file"
              first=true
              for img in $(ls $gallery/*.jpg | sort); do
                if [ "$first" = true ]; then
                  first=false
                else
                  echo "," >> "$json_file"
                fi
                filename=$(basename "$img")
                echo "  {\"url\": \"$filename\", \"alt\": \"${filename%.jpg}\"}" >> "$json_file"
              done
              echo "]" >> "$json_file"
              echo "Generated $json_file"
            fi
          done
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gallery_*/images.json
          git diff --cached --quiet || git commit -m "Auto-generated JSON files for galleries"
          git push
