name: Generate Images JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate JSON files with average colors
        run: |
          for dir in gallery_*/; do
            if [ -d "$dir" ]; then
              echo "Processing $dir..."
              node -e '
                const fs = require("fs");
                const path = require("path");
                const { getAverageColor } = require("image-average-color");

                const dir = process.argv[1];
                const files = fs.readdirSync(dir).filter(file => file.toLowerCase().endsWith(".jpg")).sort();

                const data = [];
                const promises = files.map(file => {
                  const filePath = path.join(dir, file);
                  return getAverageColor(filePath)
                    .then(color => {
                      const hexColor = "#" + color.map(c => Math.round(c).toString(16).padStart(2, "0")).join("");
                      data.push({
                        filename: file,
                        avgColor: hexColor
                      });
                    })
                    .catch(err => {
                      console.error(`Error processing ${file}:`, err);
                      data.push({
                        filename: file,
                        avgColor: "#e0e0e0"
                      });
                    });
                });

                Promise.all(promises).then(() => {
                  fs.writeFileSync(path.join(dir, "images.json"), JSON.stringify(data, null, 2));
                  console.log("images.json generated successfully.");
                });
              ' "$dir"
            fi
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Updated images.json with average colors'
          file_pattern: 'gallery_*/images.json'
